### ISSUE TITLE
yarn run dev

### ISSUE THREAD

**Issue by ghost** [IamManchanda/gulp-website#23]
gulp-webpack-master yarn run dev
yarn run v1.9.4
$ gulp dev
/Users/..................../gulp-webpack-master/gulpfile.js:215
      ), browserSync.reload);
      ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at execute (/Users/user/myProjects_Mac_OS/Bootstrap4_Template/gulp-webpack-master/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by IamManchanda** [comment]
Thanks for reporting ... will look into next weekend!
